# -*- coding: utf-8 -*-
"""LR_with_Deployment_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-bVE9ZsqMG4z1cQtZLzcw56G3JsGM2w
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the training dataset
train_df = pd.read_csv('Titanic_train.csv')
test_df = pd.read_csv('Titanic_test.csv')

train_df.info()

train_df.describe()

# Visualizations [cite: 5]
# Histogram of Age
plt.figure(figsize=(10, 5))
sns.histplot(data=train_df, x='Age', hue='Survived', kde=True)
plt.title('Distribution of Age by Survival Status')
plt.show()

# Box plot for Fare and Pclass [cite: 5]
plt.figure(figsize=(10, 5))
sns.boxplot(x='Pclass', y='Fare', data=train_df)
plt.title('Fare Distribution across Passenger Classes')
plt.show()

# Correlation Heatmap [cite: 6]
plt.figure(figsize=(12, 8))
sns.heatmap(train_df.select_dtypes(include=['number']).corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Features')
plt.show()

def preprocess_data(df):
    # Handle missing values: Impute Age with median and Embarked with mode [cite: 8]
    df['Age'] = df['Age'].fillna(df['Age'].median())
    df['Fare'] = df['Fare'].fillna(df['Fare'].median())
    df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

    # Drop irrelevant features [cite: 4]
    df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

    # Encode categorical variables: Sex and Embarked [cite: 9]
    df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)
    return df

# Apply preprocessing
# Reload the original datasets as they might have been modified in-place previously
train_df = pd.read_csv('Titanic_train.csv')
test_df = pd.read_csv('Titanic_test.csv')

train_cleaned = preprocess_data(train_df)
test_cleaned = preprocess_data(test_df)

# Align test columns with train columns (ensuring both have same encoded features)
X = train_cleaned.drop('Survived', axis=1)
y = train_cleaned['Survived']
X_test_final = test_cleaned # The test file doesn't have a 'Survived' column

print("Preprocessing complete. Train shape:", X.shape, "Test shape:", X_test_final.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pickle

# Split the original training data to evaluate locally before final test prediction [cite: 12]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Build and Train the model [cite: 11, 12]
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

# Save the model and feature names for Streamlit deployment [cite: 22]
with open('titanic_model.pkl', 'wb') as f:
    pickle.dump(log_model, f)
with open('features.pkl', 'wb') as f:
    pickle.dump(list(X.columns), f)

from sklearn.metrics import classification_report, roc_auc_score, roc_curve

# Evaluate on validation set [cite: 14]
y_pred = log_model.predict(X_val)
y_prob = log_model.predict_proba(X_val)[:, 1]

print("--- Classification Report ---")
print(classification_report(y_val, y_pred))

# ROC-AUC and Curve [cite: 14, 15]
auc_score = roc_auc_score(y_val, y_prob)
print(f"ROC-AUC Score: {auc_score:.4f}")

fpr, tpr, _ = roc_curve(y_val, y_prob)
plt.plot(fpr, tpr, label=f"ROC Curve (AUC = {auc_score:.2f})")
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.show()

# Interpret coefficients [cite: 17]
coeff_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': log_model.coef_[0]})
coeff_df = coeff_df.sort_values(by='Coefficient', ascending=False)
print(coeff_df)

"""INSIGHTS
- Sex_male has a strongly negative coefficient, meaning being male significantly decreases survival probability.
- Pclass has a negative coefficient, implying higher class numbers (lower status) reduce survival chances.
- Fare has a positive coefficient, indicating higher-paying passengers had better survival odds.

"""

!pip install streamlit

!npm install -g localtunnel -U

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import pickle
# import numpy as np

# Load the trained model and features saved in previous steps
try:
    model = pickle.load(open('titanic_model.pkl', 'rb'))
    feature_names = pickle.load(open('features.pkl', 'rb'))
except FileNotFoundError:
    st.error("Model files not found. Please run the training cells first.")

st.set_page_config(page_title="Titanic Survival Predictor")
st.title("🚢 Titanic Survival Prediction")

# User Inputs based on dataset features
st.sidebar.header("Passenger Details")
pclass = st.sidebar.selectbox("Travel Class (1 = 1st, 2 = 2nd, 3 = 3rd)", [1, 2, 3])
sex = st.sidebar.radio("Sex", ["female", "male"])
age = st.sidebar.slider("Age", 0, 80, 25)
sibsp = st.sidebar.number_input("Siblings/Spouses Aboard", 0, 8, 0)
parch = st.sidebar.number_input("Parents/Children Aboard", 0, 6, 0)
fare = st.sidebar.number_input("Fare Paid", 0.0, 512.0, 32.0)
embarked = st.sidebar.selectbox("Port of Embarkation", ["C", "Q", "S"])

# Formatting input for the model
data = {
    'Pclass': pclass,
    'Age': age,
    'SibSp': sibsp,
    'Parch': parch,
    'Fare': fare,
    'Sex_male': 1 if sex == 'male' else 0,
    'Embarked_Q': 1 if embarked == 'Q' else 0,
    'Embarked_S': 1 if embarked == 'S' else 0
}

input_df = pd.DataFrame([data])

if st.button("Predict Survival"):
    prediction = model.predict(input_df)
    probability = model.predict_proba(input_df)[0][1]

    if prediction[0] == 1:
        st.success(f"The passenger is likely to survive! (Confidence: {probability:.2%})")
    else:
        st.error(f"The passenger is unlikely to survive. (Survival Probability: {probability:.2%})")

# Run this cell to create the app.py file
app_code = """
import streamlit as st
import pandas as pd
import pickle

# Load model and features
model = pickle.load(open('titanic_model.pkl', 'rb'))
feature_names = pickle.load(open('features.pkl', 'rb'))

st.title("Titanic Survival Prediction App")
st.write("Enter passenger details to predict survival probability.")

# User Inputs [cite: 22]
pclass = st.selectbox("Passenger Class (1=1st, 2=2nd, 3=3rd)", [1, 2, 3])
age = st.slider("Age", 0, 100, 25)
sibsp = st.number_input("Siblings/Spouses Aboard", 0, 10, 0)
parch = st.number_input("Parents/Children Aboard", 0, 10, 0)
fare = st.number_input("Fare Paid", 0.0, 600.0, 32.0)
sex = st.selectbox("Sex", ["male", "female"])
embarked = st.selectbox("Port of Embarkation", ["S", "C", "Q"])

# Prepare input for prediction
data = {
    'Pclass': pclass, 'Age': age, 'SibSp': sibsp, 'Parch': parch, 'Fare': fare,
    'Sex_male': 1 if sex == 'male' else 0,
    'Embarked_Q': 1 if embarked == 'Q' else 0,
    'Embarked_S': 1 if embarked == 'S' else 0
}
input_df = pd.DataFrame([data])

if st.button("Predict"):
    prediction = model.predict(input_df)[0]
    prob = model.predict_proba(input_df)[0][1]

    if prediction == 1:
        st.success(f"Survived! (Probability: {prob:.2f})")
    else:
        st.error(f"Did Not Survive. (Probability of survival: {prob:.2f})")
"""

with open('app.py', 'w') as f:
    f.write(app_code)

print("app.py has been created. You can now deploy this to Streamlit Share or run it locally[cite: 21, 23].")

!wget -q -O - ipv4.icanhazip.com

!streamlit run app.py & npx localtunnel --port 8501

